### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by csm** [bjeanes/go-edn#1]
Howdy. I've been looking at this project for something I'm working on, and have a [fork](https://github.com/csm/go-edn) that contains some improvements already.

Would you consider adding some licensing terms, so I can use this for something meaningful? Naturally, some kind of permissive open-source license would be most agreeable :)

(Also, I could make a pull request, if you're interested in keeping the main project under your account)

**Comment by rschmitt** [comment]
Might I suggest [CC0](https://creativecommons.org/about/cc0)?

**Comment by bjeanes** [comment]
@csm @rschmitt I added an MPL 2.0 license in aa12bdc743c25015976af8a52a14db1755fd10fe. I'm not dogmatic about choice of license – it's been what I've been using recently. If it doesn't fit your needs, feel free to re-open and let me know a bit more about your situation and I can think about some other choices here, including CC0. Thanks!

Side-note: @csm, I noticed you removed the generated parser files. I'm pretty pedantic about not committing generated files myself, but it's my understanding that `go get` still doesn't have any way to run a pre-compilation step to create that file so I was committing them so that consuming the library was easier. It's been more than a year since I did much Go, have things changed?

**Comment by csm** [comment]
I messed some things up, and was still planning on checking in the generated files. I'm still learning some of Go's "unique" ways of doing things.

Thanks for adding a license! MPL should be just fine.
